name: Java CI with Maven (Matrix)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [11, 17, 21]
        exclude:
          - os: macos-latest
           # java: 11  # исключим, если не нужно

    name: Test on ${{ matrix.os }} with Java ${{ matrix.java }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn clean test